name: CI/CD - Install & Generate Lockfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Untuk commit lockfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install   # BUAT package-lock.json OTOMATIS

      - name: Commit package-lock.json
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add package-lock.json
          git diff --staged --quiet || git commit -m "chore: add package-lock.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test (optional)
        run: npm test || echo "No tests"
